#!/usr/bin/env sh

# BSD 3-Clause License
# 
# Copyright (c) 2023, Justin Teague
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -eu

LC_ALL=C

# Usage:
# ddnsbot -c <path/to/config> -T <path/to/token> -z <zone:optional> -d <domain>
# Check for dependencies curl or wget, jq
# Check for configuration
# Parse flags
#

# function: get zone from domain
zones_from_domain() {
  # Usage: <domains>
  _domain="${1?zones_from_domain: no domain specified}"
  _zones=""
  while true; do
    _domain=${_domain#*.}
    _zones="$_domain ${_zones:-}"
    case "$_domain" in 
      *.*) true ;;
      *) printf %s\\n "$_zones" ; return ;;
    esac
  done
}

# function: check if domain exists

# Configuration is for cron jobs in a simple ini format file
# [ <zone> ]
# api_token=xxxxxxxx
# domain=<domain>
# domain=<domain>

# function: save commands to a ini configuration file

"$@"
